[features]
resolution = true
skip-lint = false

[programs.localnet]
mealtrust_state = "AWyYvJCuYwn2FQvQj4P3nz3vmTgn8HgJBY6itReuy1pu"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
